import type { WorkshopState, FitScore, RankedItem } from './types'

function uid() {
  return `${Date.now()}-${Math.random().toString(36).slice(2, 7)}`
}

export function createEmptyWorkshop(): WorkshopState {
  return {
    projectName: '',
    currentStep: 0,
    segments: [],
    jtbdStatements: [],
    pains: [],
    gains: [],
    valueMap: {
      productsServices: [''],
      painRelievers: [],
      gainCreators: [],
    },
    fitScores: [],
    bmc: {
      customerSegments: '',
      valueProposition: '',
      channels: '',
      customerRelationships: '',
      revenueStreams: '',
      keyResources: '',
      keyActivities: '',
      keyPartners: '',
      costStructure: '',
    },
  }
}

export function jtbdFormatted(j: {
  situation: string
  job: string
  outcome: string
}): string {
  return `When ${j.situation}, I want to ${j.job}, so I can ${j.outcome}`
}

export function whoWhenWhere(seg: { name: string; when: string; where: string; situation: string }) {
  return `**Who:** ${seg.name}\n**When:** ${seg.when}\n**Where:** ${seg.where}\n**Situation:** ${seg.situation}`
}

export function generateFitFeedback(
  pains: RankedItem[],
  gains: RankedItem[],
  fitScores: FitScore[],
  valueMap: WorkshopState['valueMap']
): string[] {
  const feedback: string[] = []

  const highPains = pains.filter((p) => p.importance >= 4)
  for (const pain of highPains) {
    const score = fitScores.find((f) => f.itemId === pain.id && f.type === 'pain')
    const hasReliever = valueMap.painRelievers.some((pr) => pr.painId === pain.id && pr.description.trim())
    if (!hasReliever || score?.coverage === 'low') {
      feedback.push(`⚠️ Pain สำคัญ: "${pain.text}" — ยังไม่มี Pain Reliever ที่ชัดเจน`)
    }
  }

  const highGains = gains.filter((g) => g.importance >= 4)
  for (const gain of highGains) {
    const score = fitScores.find((f) => f.itemId === gain.id && f.type === 'gain')
    const hasCreator = valueMap.gainCreators.some((gc) => gc.gainId === gain.id && gc.description.trim())
    if (!hasCreator || score?.coverage === 'low') {
      feedback.push(`⚠️ Gain สำคัญ: "${gain.text}" — ยังไม่มี Gain Creator ที่ตอบชัด`)
    }
  }

  const wellCovered = fitScores.filter((f) => f.coverage === 'high').length
  if (wellCovered >= 3) {
    feedback.push('✅ Problem–Solution Fit ดี — หลาย Pain/Gain ถูกตอบด้วย Value Map')
  }

  if (feedback.length === 0) {
    feedback.push('✅ Value Map ครอบคลุม Pain/Gain หลักในระดับที่น่าพอใจ')
  }

  return feedback
}

export function generateInsightText(state: WorkshopState): string {
  const topSegment = state.segments[0]?.name ?? '—'
  const topPain = [...state.pains].sort((a, b) => b.importance - a.importance)[0]
  const topGain = [...state.gains].sort((a, b) => b.importance - a.importance)[0]
  const mainJtbd = state.jtbdStatements[0]
  const gaps = generateFitFeedback(state.pains, state.gains, state.fitScores, state.valueMap)
  const mainGap = gaps.find((g) => g.startsWith('⚠️')) ?? 'ไม่พบช่องว่างใหญ่ — พร้อมทดสอบ Product–Market Fit'

  return [
    `Segment หลักของคุณคือ **${topSegment}** — โฟกus JTBD-first แทน demographic ล้วน`,
    mainJtbd
      ? `Job สำคัญสุด: "${jtbdFormatted(mainJtbd)}"`
      : 'ยังไม่ได้กำหนด JTBD statement หลัก',
    topPain ? `Pain ที่ต้องแก้ก่อน: "${topPain.text}" (ความสำคัญ ${topPain.importance}/5)` : '',
    topGain ? `Gain ที่ลูกค้าโหยหา: "${topGain.text}" (ความสำคัญ ${topGain.importance}/5)` : '',
    `ช่องว่างหลักใน Value Proposition: ${mainGap.replace('⚠️ ', '')}`,
  ]
    .filter(Boolean)
    .join('\n\n')
}

export function generateMarkdown(state: WorkshopState): string {
  const { projectName, segments, jtbdStatements, pains, gains, valueMap, bmc } = state
  const fitFeedback = generateFitFeedback(state.pains, state.gains, state.fitScores, state.valueMap)

  let md = `# ${projectName || 'Strategy Workshop'}\n\n`
  md += `> Generated by Aetros Strategy Workshop · JTBD → VPC → BMC\n\n`

  md += `## Insight Summary\n\n${generateInsightText(state)}\n\n---\n\n`

  md += `## Jobs-to-Be-Done\n\n`
  for (const seg of segments) {
    md += `### ${seg.name}\n\n${whoWhenWhere(seg)}\n\n`
    const jobs = jtbdStatements.filter((j) => j.segmentId === seg.id)
    for (const j of jobs) {
      md += `- **Statement:** ${jtbdFormatted(j)}\n`
      md += `  - Functional: ${j.functional || '—'}\n`
      md += `  - Emotional: ${j.emotional || '—'}\n`
      md += `  - Social: ${j.social || '—'}\n\n`
    }
  }

  md += `## Value Proposition Canvas\n\n`
  md += `### Customer Profile\n\n`
  md += `#### Pains\n\n`
  for (const p of pains.sort((a, b) => b.importance - a.importance)) {
    md += `- [${p.importance}/5] ${p.text}${p.dimension ? ` _(${p.dimension})_` : ''}\n`
  }
  md += `\n#### Gains\n\n`
  for (const g of gains.sort((a, b) => b.importance - a.importance)) {
    md += `- [${g.importance}/5] ${g.text}${g.dimension ? ` _(${g.dimension})_` : ''}\n`
  }

  md += `\n### Value Map\n\n`
  md += `#### Products & Services\n\n`
  valueMap.productsServices.filter(Boolean).forEach((p) => { md += `- ${p}\n` })
  md += `\n#### Pain Relievers\n\n`
  valueMap.painRelievers.forEach((pr) => {
    const pain = pains.find((p) => p.id === pr.painId)
    md += `- **${pain?.text ?? pr.painId}:** ${pr.description}\n`
  })
  md += `\n#### Gain Creators\n\n`
  valueMap.gainCreators.forEach((gc) => {
    const gain = gains.find((g) => g.id === gc.gainId)
    md += `- **${gain?.text ?? gc.gainId}:** ${gc.description}\n`
  })

  md += `\n## Product–Market Fit Check\n\n`
  fitFeedback.forEach((f) => { md += `- ${f}\n` })

  md += `\n## Business Model Canvas\n\n`
  md += `| Block | Content |\n|-------|--------|\n`
  const bmcRows: [string, keyof typeof bmc][] = [
    ['Customer Segments', 'customerSegments'],
    ['Value Proposition', 'valueProposition'],
    ['Channels', 'channels'],
    ['Customer Relationships', 'customerRelationships'],
    ['Revenue Streams', 'revenueStreams'],
    ['Key Resources', 'keyResources'],
    ['Key Activities', 'keyActivities'],
    ['Key Partners', 'keyPartners'],
    ['Cost Structure', 'costStructure'],
  ]
  for (const [label, key] of bmcRows) {
    md += `| ${label} | ${bmc[key] || '—'} |\n`
  }

  return md
}

export function generateCSV(state: WorkshopState): string {
  const headers = [
    'Segment',
    'JTBD',
    'Pain',
    'Pain Importance',
    'Gain',
    'Gain Importance',
    'Product/Feature',
    'Pain Reliever',
    'Gain Creator',
    'Fit Coverage',
  ]

  const rows: string[][] = []
  const escape = (s: string) => `"${s.replace(/"/g, '""')}"`

  for (const seg of state.segments) {
    const jtbd = state.jtbdStatements.find((j) => j.segmentId === seg.id)
    const jtbdText = jtbd ? jtbdFormatted(jtbd) : ''
    const segPains = state.pains.filter((p) => p.segmentId === seg.id)
    const segGains = state.gains.filter((g) => g.segmentId === seg.id)
    const maxRows = Math.max(segPains.length, segGains.length, 1)

    for (let i = 0; i < maxRows; i++) {
      const pain = segPains[i]
      const gain = segGains[i]
      const pr = pain ? state.valueMap.painRelievers.find((r) => r.painId === pain.id) : undefined
      const gc = gain ? state.valueMap.gainCreators.find((c) => c.gainId === gain.id) : undefined
      const fitP = pain ? state.fitScores.find((f) => f.itemId === pain.id)?.coverage ?? '' : ''
      const fitG = gain ? state.fitScores.find((f) => f.itemId === gain.id)?.coverage ?? '' : ''

      rows.push([
        i === 0 ? seg.name : '',
        i === 0 ? jtbdText : '',
        pain?.text ?? '',
        pain ? String(pain.importance) : '',
        gain?.text ?? '',
        gain ? String(gain.importance) : '',
        state.valueMap.productsServices[i] ?? '',
        pr?.description ?? '',
        gc?.description ?? '',
        fitP || fitG,
      ])
    }
  }

  return [headers.map(escape).join(','), ...rows.map((r) => r.map(escape).join(','))].join('\n')
}

export { uid }
